source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem "pg"


group :test, :development do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'rails_layout' # foundation
end
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'foundation-rails'
end

gem 'jquery-rails'

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'faker'
end

gem "email_spec", :group => :test
